// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

#nullable disable

namespace WebBanHang.Migrations
{
    [DbContext(typeof(WebBanHangContext))]
    [Migration("20260426071624_InitialCreate_Customer")]
    partial class InitialCreate_Customer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("WebBanHang.Models.TbAbout", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("tb_About", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbBrand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Brand", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Config", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbContact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Contact", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("tb_Customer", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbCustomerAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddressID");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.ToTable("tb_CustomerAddress", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbFeedback", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.ToTable("tb_Feedback", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbFooter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tb_Footer", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("InvoiceId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_tb_Invoice_SupplierID");

                    b.ToTable("tb_Invoice", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbInvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InvoiceID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quanlity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex(new[] { "ProductId" }, "IX_tb_InvoiceDetail_ProductID");

                    b.ToTable("tb_InvoiceDetail", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Menu", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OrderID");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddressID");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Discount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Orderdate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VoucherID");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "AddressId" }, "IX_tb_Orders_AddressID");

                    b.HasIndex(new[] { "CustomerId" }, "IX_tb_Orders_CustomerID");

                    b.HasIndex(new[] { "VoucherId" }, "IX_tb_Orders_VoucherID");

                    b.ToTable("tb_Orders", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbOrderDetail", b =>
                {
                    b.Property<int>("OderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Quanlity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OderId", "ProductId");

                    b.HasIndex(new[] { "ProductId" }, "IX_tb_OrderDetail_ProductID");

                    b.ToTable("tb_OrderDetail", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerID");

                    b.Property<string>("ExprireData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_PasswordReset", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPorduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<int?>("BrainId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BrainID");

                    b.Property<int?>("CateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CateID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("ntext");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Quanlity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeiTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierID");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "BrainId" }, "IX_tb_Porduct_BrainID");

                    b.HasIndex(new[] { "CateId" }, "IX_tb_Porduct_CateID");

                    b.HasIndex(new[] { "SupplierId" }, "IX_tb_Porduct_SupplierID");

                    b.ToTable("tb_Porduct", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PostID");

                    b.Property<int?>("CateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CateID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("ntext");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeiTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId");

                    b.HasIndex(new[] { "CateId" }, "IX_tb_Post_CateID");

                    b.ToTable("tb_Post", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostCatetogy", b =>
                {
                    b.Property<int>("CateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CateID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentID");

                    b.Property<string>("Seotitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CateId");

                    b.ToTable("tb_PostCatetogy.", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommentID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PostID");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "PostId" }, "IX_tb_PostComment_PostID");

                    b.ToTable("tb_PostComment", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostTag", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PostID");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TagID");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex(new[] { "TagId" }, "IX_tb_PostTag_TagID");

                    b.ToTable("tb_PostTag", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbProductCategory", b =>
                {
                    b.Property<int>("CateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CateID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadescriptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentID");

                    b.Property<string>("Seotitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CateId");

                    b.ToTable("tb_ProductCategory", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbProductComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CommentID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_tb_ProductComment_CustomerID");

                    b.HasIndex(new[] { "ProductId" }, "IX_tb_ProductComment_ProductID");

                    b.ToTable("tb_ProductComment", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbSlide", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tb_Slide", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbSupplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Supplier", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tb_Tag", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.TbVoucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VoucherID");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Quanlity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoucherId");

                    b.ToTable("tb_Voucher", (string)null);
                });

            modelBuilder.Entity("WebBanHang.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebBanHang.Models.TbInvoice", b =>
                {
                    b.HasOne("WebBanHang.Models.TbSupplier", "Supplier")
                        .WithMany("TbInvoices")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebBanHang.Models.TbInvoiceDetail", b =>
                {
                    b.HasOne("WebBanHang.Models.TbInvoice", "Invoice")
                        .WithMany("TbInvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .IsRequired();

                    b.HasOne("WebBanHang.Models.TbPorduct", "Product")
                        .WithMany("TbInvoiceDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Models.TbOrder", b =>
                {
                    b.HasOne("WebBanHang.Models.TbCustomerAddress", "Address")
                        .WithMany("TbOrders")
                        .HasForeignKey("AddressId");

                    b.HasOne("WebBanHang.Models.TbCustomer", "Customer")
                        .WithMany("TbOrders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("WebBanHang.Models.TbVoucher", "Voucher")
                        .WithMany("TbOrders")
                        .HasForeignKey("VoucherId");

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WebBanHang.Models.TbOrderDetail", b =>
                {
                    b.HasOne("WebBanHang.Models.TbOrder", "Oder")
                        .WithMany("TbOrderDetails")
                        .HasForeignKey("OderId")
                        .IsRequired();

                    b.HasOne("WebBanHang.Models.TbPorduct", "Product")
                        .WithMany("TbOrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.Navigation("Oder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPorduct", b =>
                {
                    b.HasOne("WebBanHang.Models.TbBrand", "Brain")
                        .WithMany("TbPorducts")
                        .HasForeignKey("BrainId");

                    b.HasOne("WebBanHang.Models.TbProductCategory", "Cate")
                        .WithMany("TbPorducts")
                        .HasForeignKey("CateId");

                    b.HasOne("WebBanHang.Models.TbSupplier", "Supplier")
                        .WithMany("TbPorducts")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Brain");

                    b.Navigation("Cate");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPost", b =>
                {
                    b.HasOne("WebBanHang.Models.TbPostCatetogy", "Cate")
                        .WithMany("TbPosts")
                        .HasForeignKey("CateId");

                    b.Navigation("Cate");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostComment", b =>
                {
                    b.HasOne("WebBanHang.Models.TbPost", "Post")
                        .WithMany("TbPostComments")
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostTag", b =>
                {
                    b.HasOne("WebBanHang.Models.TbTag", "Tag")
                        .WithMany("TbPostTags")
                        .HasForeignKey("TagId")
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebBanHang.Models.TbProductComment", b =>
                {
                    b.HasOne("WebBanHang.Models.TbCustomer", "Customer")
                        .WithMany("TbProductComments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("WebBanHang.Models.TbPorduct", "Product")
                        .WithMany("TbProductComments")
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Models.TbBrand", b =>
                {
                    b.Navigation("TbPorducts");
                });

            modelBuilder.Entity("WebBanHang.Models.TbCustomer", b =>
                {
                    b.Navigation("TbOrders");

                    b.Navigation("TbProductComments");
                });

            modelBuilder.Entity("WebBanHang.Models.TbCustomerAddress", b =>
                {
                    b.Navigation("TbOrders");
                });

            modelBuilder.Entity("WebBanHang.Models.TbInvoice", b =>
                {
                    b.Navigation("TbInvoiceDetails");
                });

            modelBuilder.Entity("WebBanHang.Models.TbOrder", b =>
                {
                    b.Navigation("TbOrderDetails");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPorduct", b =>
                {
                    b.Navigation("TbInvoiceDetails");

                    b.Navigation("TbOrderDetails");

                    b.Navigation("TbProductComments");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPost", b =>
                {
                    b.Navigation("TbPostComments");
                });

            modelBuilder.Entity("WebBanHang.Models.TbPostCatetogy", b =>
                {
                    b.Navigation("TbPosts");
                });

            modelBuilder.Entity("WebBanHang.Models.TbProductCategory", b =>
                {
                    b.Navigation("TbPorducts");
                });

            modelBuilder.Entity("WebBanHang.Models.TbSupplier", b =>
                {
                    b.Navigation("TbInvoices");

                    b.Navigation("TbPorducts");
                });

            modelBuilder.Entity("WebBanHang.Models.TbTag", b =>
                {
                    b.Navigation("TbPostTags");
                });

            modelBuilder.Entity("WebBanHang.Models.TbVoucher", b =>
                {
                    b.Navigation("TbOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
